// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RealEstatesAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20210617090026_dixedIssureWithUsername")]
    partial class dixedIssureWithUsername
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("634d3bb7-8bb2-4758-a2aa-200442a8211c"),
                            Content = "I dont wan't this house, im just here to read the comments!",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(4636),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("988d0bfe-d832-4351-a11e-e872bf7cd40c"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 4, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(8863),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("73f400cc-87f3-4f93-854a-7304545b6f03"),
                            Content = "Are you sure this is the right address?",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(8930),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("6a5bbb67-0c94-4c2c-b5c2-e9fb1a1a36c5"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(8965),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("62f9b171-5216-4fed-9509-c10c889546ad"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9034),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("c84f2e70-b169-469d-9907-f5bc552bc335"),
                            Content = "This property is so cool!",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9060),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("71a7e92d-a030-4d3f-889e-7ede522445d2"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 6, 12, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9084),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("ce438365-1b00-4cff-bb1f-f7f9f46c7ae6"),
                            Content = "How many carpenters does it take to unscrew a lightbulb?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9109),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("ecdfe2ef-43ca-474f-932e-65aa9ce95d82"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9134),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("4e05fe91-8817-4ceb-b8fa-99350c7aef8e"),
                            Content = "Are you sure this is the right address?",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9157),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("83be551f-2f20-4df0-9ee8-e8de7f443207"),
                            Content = "Atleast the carpets are nice!",
                            CreatedOn = new DateTime(2021, 6, 4, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9182),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("df2b9f79-8ac3-4dca-a74e-4cfdb489011a"),
                            Content = "This is a nice house!",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9206),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("1255a8eb-960c-47b5-8c43-203fb84f8637"),
                            Content = "Can this house even fit one person?",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9229),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("bd1d8b68-2f68-494d-a671-d372fb96ff22"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9255),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("59a63663-36f5-4481-86a2-47a207d9fa66"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9282),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("0e97c4af-6f5e-407b-89f3-dd13d849d750"),
                            Content = "Great use of space!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9305),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("03a34cea-b733-45e4-9fe9-487e3c723f3c"),
                            Content = "Great use of space!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9318),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("0403f5ba-2ee0-4e24-bf45-553037fc6c6f"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9339),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("1aa40b0b-b050-4a17-85ff-5b02bc317170"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9370),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("557a52c4-31f2-40fd-91e0-9396eb96318e"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9468),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("c65f7e80-453d-4c8f-afa3-5d195168f5ff"),
                            Content = "I hope this property gets termites!",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9490),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("2073479b-d131-4932-ba96-afbf2f9f1416"),
                            Content = "Wow, this house sucks!",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9501),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("52fbb5ac-23b1-4398-9684-26c0f6880520"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9523),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("7c38f735-da4f-47d9-97fd-4abe0f747172"),
                            Content = "Atleast the carpets are nice!",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9550),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("8dd28108-ac6f-4337-b09a-f5f865bc1b79"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 8, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9581),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("9605b50d-5d35-4741-9630-e47b97bcd479"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 13, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9612),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("bf2fe3bd-4c51-424a-b276-7c8e0ab9c459"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 12, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9644),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("ed8b4409-6b8b-441b-ab74-8b0335acb121"),
                            Content = "This is a nice house!",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9674),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("37e83fac-3b78-4ab1-8738-c3bfc4c56983"),
                            Content = "Wow, this house sucks!",
                            CreatedOn = new DateTime(2021, 6, 4, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9703),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("f544f1c8-af7e-451f-a552-ad0cf9a694cf"),
                            Content = "Can this house even fit one person?",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9736),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("e62428b3-cbc8-474f-8ca6-a1807037d89d"),
                            Content = "Who's there?",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9766),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("502f6097-e64c-4f21-9842-43294803f13c"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9797),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("8c119450-9afd-4631-a739-711a59281eee"),
                            Content = "Just beastly =)",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9827),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("91d3567f-d9e9-41fd-8dc5-d63411b111fb"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9858),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("72814ec8-5c78-4e15-a8f4-0cae19d36646"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9888),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("b0bd316e-3106-4cbc-bb4d-d039db46df56"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9918),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("a0ac255f-57c9-4a15-ba1c-d338845c9140"),
                            Content = "What is wrong with people? This is a chat for the property.",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9949),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("738dbf01-af71-414f-b50b-43498b8cae16"),
                            Content = "I'm in!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 60, DateTimeKind.Local).AddTicks(9980),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("4fdad378-9b7c-432e-90ca-381b1cb5c44c"),
                            Content = "This is to expensive? ",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(10),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("a63eff1e-d05b-4609-bc70-2874b788c109"),
                            Content = "WHAT?! This is my house! Im not selling my house?..",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(41),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("07a22b25-a701-4fe4-82fc-ca462616880c"),
                            Content = "Just beastly =)",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(71),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("404f0986-6a0b-44d6-a466-17fba2eb7568"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(102),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("f580ca02-8d6a-44c3-9fac-69e805bfe8b0"),
                            Content = "This property is so cool!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(136),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("385bf01c-6ae1-4f33-9414-032b1bd84e74"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(167),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("a0b54d62-c617-4f92-a896-267249d99b33"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(197),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("4a21b014-dfb0-4408-8863-5416da785a7f"),
                            Content = "I'm in!",
                            CreatedOn = new DateTime(2021, 6, 13, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(227),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("db84db1c-6018-469b-91d2-74a81e1d6fef"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(257),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("1d9db001-ae5f-409c-b006-c402f49363b0"),
                            Content = "This is to expensive? ",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(285),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("9fe27cd7-245a-4c48-8b13-52c159a6c357"),
                            Content = "I hope this property gets termites!",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(318),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("4fe00604-e488-4ed9-a262-3935c80e0941"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(345),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("ace2141e-c784-4f89-b1c7-f6ddc3b2742f"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(375),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("002a3077-d886-4aec-834d-ae00a3739d74"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(405),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("fb33ac79-fa54-4202-95fe-29bbf886a086"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 8, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(434),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("3cd27f55-c4fa-4091-97a9-8eaeda23d4c8"),
                            Content = "I'm gonna rob this house!",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(467),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("a3787355-cd69-469e-9478-d5fadfe49c82"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(497),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("53a36a6a-9ab4-4147-8a2d-3caaca9e934a"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(528),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("de854650-9e5a-44b6-a480-f9075b81fd97"),
                            Content = "PLEASE ADD ME ON FORTNITE! MY GAMERTAG IS BEASTKILLER_5343",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(558),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("1ca17c06-b6b0-454b-8994-2ea17ca8c376"),
                            Content = "How many carpenters does it take to unscrew a lightbulb?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(590),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("fd9688c4-7d72-49ce-9c86-fdd737084eb5"),
                            Content = "Is the rat-infestation included in the price?",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(623),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("2a22598c-5ba9-44bb-aa2c-0b3237c69d19"),
                            Content = "I'm in!",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(654),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("eae70de0-3fb1-4e6b-aa2d-67c278854dac"),
                            Content = "Holy Moly, is this where the kardashians live?",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(685),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("cb5f189e-1a07-42e9-9b01-3ca4f0da94cb"),
                            Content = "Who's there?",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(715),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("0beb6a4b-614c-4c72-942b-fd0b8c4c295c"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(751),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("e35b63d0-da4d-4c55-9e3c-8668a7f19d6c"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 4, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(782),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("98f7713b-16de-4a35-9d54-81d641686889"),
                            Content = "How many carpenters does it take to unscrew a lightbulb?",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(813),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("80b00405-fc16-42ea-ae44-678f3c037f48"),
                            Content = "Is the rat-infestation included in the price?",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(844),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("b9d74c45-9f5c-4a2e-8e70-470f2d8a98ba"),
                            Content = "Atleast the carpets are nice!",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(874),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("ffe26a5a-cdc0-4f41-983b-1e417cebc69a"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(904),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("9e27527d-d392-4488-b4e0-995900c25233"),
                            Content = "WHAT?! This is my house! Im not selling my house?..",
                            CreatedOn = new DateTime(2021, 6, 8, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(935),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("957a7066-0309-4a93-b424-e76c791459be"),
                            Content = "Holy Moly, is this where the kardashians live?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(966),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("2b545cd3-d8ce-4662-982c-92aaf5a65fe4"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1308),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("b2fd98cd-5be3-4c89-b08d-0249c2c9d499"),
                            Content = "I'm in!",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1341),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("09560698-875d-46fe-8604-37b83ee357de"),
                            Content = "Who's there?",
                            CreatedOn = new DateTime(2021, 6, 15, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1373),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("a905b361-f29c-41f8-9565-91bbb52cd529"),
                            Content = "I'm gonna rob this house!",
                            CreatedOn = new DateTime(2021, 6, 12, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1402),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("0cabc01b-093f-4ed5-b35e-e63734c96116"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1429),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("7d533fcc-47b1-4ec8-a96b-b5ef2db2669d"),
                            Content = "Nice use of ivory in this shot :-)",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1449),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("7431a59f-5db0-400e-9ebe-f43a423b3e86"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1475),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("dd8e5465-6334-4d87-b073-17029686c936"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1496),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("a93c44d2-18d2-4d63-bd59-928e3e657d05"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1535),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("4ef73023-e3a6-42a8-9d7f-859b3dfd85db"),
                            Content = "Atleast the carpets are nice!",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1563),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("7557de64-b5fb-4542-8ad4-413c5afba537"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1587),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("bff08946-1d12-4f6b-bfc6-c3ad93ae9e43"),
                            Content = "Nice use of ivory in this shot :-)",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1611),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("0dd4916a-db56-4d84-83f1-c6247b578990"),
                            Content = "Is the rat-infestation included in the price?",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1637),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("088b37c4-394b-4b10-bfa9-3cd65d9c6334"),
                            Content = "This is to expensive? ",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1662),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("598f1fec-6814-47f8-833e-305b4e86eb9f"),
                            Content = "Don't go here! This place is haunted!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1689),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("b293a801-db97-4326-a81e-aec69bf25ec6"),
                            Content = "This is a nice house!",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1715),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("ccc3ca0b-6f5c-4843-96c3-177014a06983"),
                            Content = "Are you sure this is the right address?",
                            CreatedOn = new DateTime(2021, 6, 12, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1743),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("a75668df-9867-4e2e-aa77-319039b2e835"),
                            Content = "Just beastly =)",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1769),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("5e934277-ac21-4ab6-97b1-d9f1f3d958be"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1796),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("dca93398-9124-41c5-aa16-5b5635d84626"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1824),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("c30f3ff3-a987-4d2b-8ccd-39d85028815f"),
                            Content = "I dont wan't this house, im just here to read the comments!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1852),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("3b3edc72-ea89-46b0-a8a6-2b220b0dd28e"),
                            Content = "Holy Moly, is this where the kardashians live?",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1885),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("5d2ac5c9-f459-4829-9565-18132aa7e7d1"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1914),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("690079f1-f6f9-4255-9683-38cbc6963a11"),
                            Content = "Why is this even up here? Should be taken down!",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1942),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("ca16d403-cafb-4087-b6c6-70c1b43779cc"),
                            Content = "What is wrong with people? This is a chat for the property.",
                            CreatedOn = new DateTime(2021, 6, 12, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(1973),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("14d3bfe8-0731-4c73-8510-199fe67428f9"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2002),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("932e232b-d14f-4bc5-b2ef-19f631165b70"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2031),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("d72e5059-c116-48fe-802c-9e7bd4373ed2"),
                            Content = "Great use of space!",
                            CreatedOn = new DateTime(2021, 6, 13, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2059),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("3b629381-3535-4765-b644-5db1ce900d13"),
                            Content = "PLEASE ADD ME ON FORTNITE! MY GAMERTAG IS BEASTKILLER_5343",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2090),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("9cdbd1b7-aa3d-48cf-8fc6-e4066320a0bd"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2122),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("71386bff-86c6-4a3a-b700-916e28c62aef"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2153),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("2f380826-31b7-4325-9e2a-8d807e3fc251"),
                            Content = "What is wrong with people? This is a chat for the property.",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2182),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("a4e8538d-3ea0-45e4-865c-c159c543f85f"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 7, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2212),
                            RealEstateId = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("9034d3c6-2217-432f-95ba-53e825c50513"),
                            Content = "Can this house even fit one person?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2244),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("51d9ec4f-9885-4003-84f9-5d8e4e5a20c5"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 6, 8, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2276),
                            RealEstateId = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("fa81b7fe-7252-45df-bb2c-917a7b461d5c"),
                            Content = "Don't go here! This place is haunted!",
                            CreatedOn = new DateTime(2021, 6, 13, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2305),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("6915a35c-fbf9-434c-bd8b-d50d7a65749f"),
                            Content = "Knock, knock!",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2334),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("4383cea1-d521-4eab-9d90-70901330d481"),
                            Content = "Holy Moly, is this where the kardashians live?",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2362),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("686f2788-6a65-4c48-90e5-181b9355bb36"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 5, 31, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2396),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("a463508b-62ed-4709-a2d5-7390284d0dca"),
                            Content = "Anyone wants to go on a date? Im up for it!",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2427),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("7ea39069-2727-438b-8004-b72bc3315f22"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 8, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2458),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("027c2254-35b7-4601-9d3c-245795c2d6e7"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2487),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("63d07933-f272-4fce-8273-feddbe0e5cb3"),
                            Content = "PLEASE ADD ME ON FORTNITE! MY GAMERTAG IS BEASTKILLER_5343",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2520),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("7f3ec16d-5c7d-4e11-8c10-5eed6f8b6732"),
                            Content = "Are you sure this is the right address?",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2551),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("42523f11-c78b-4ad6-a8a4-12b0da97f35d"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2579),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("7358eb75-92a8-47bc-adac-d245fada72d2"),
                            Content = "This property is so cool!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2609),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("34839a66-96fc-4fc4-9751-56d7a290c516"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2643),
                            RealEstateId = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("2c03cfe7-eeb0-43d5-ae48-2cb9a95b2c67"),
                            Content = "I think I'm crying. It's that beastly.",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2674),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("b64729db-0eb3-46dd-8cca-dafc7639ab5b"),
                            Content = "Don't go here! This place is haunted!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2702),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("ce73655b-489a-4322-800b-e5421bf3f5f0"),
                            Content = "What is wrong with people? This is a chat for the property.",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2732),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("0f6d7332-2381-4147-8155-bc9c05d76fb4"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2762),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("0cc8c8d8-e0e3-4dc3-9ec8-7b97fc560fac"),
                            Content = "Wow, this house sucks!",
                            CreatedOn = new DateTime(2021, 6, 9, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2790),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("9d2bab9e-3b40-4111-bcda-8d41ca53cf2c"),
                            Content = "Don't go here! This place is haunted!",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2818),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("ebcd509b-7b9b-4046-a8e3-a2c15db4650c"),
                            Content = "Why would you ever wanna buy this garbage house?",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2847),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("0ec9bced-0e92-4160-8114-f6651c5fc4a7"),
                            Content = "Can this house even fit one person?",
                            CreatedOn = new DateTime(2021, 6, 6, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2879),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("49627a00-321f-45de-b7f1-0949495a8ffc"),
                            Content = "The creator of this website seems really smart!",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2908),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("7e404a16-7ea2-45b5-9c2d-08b1e01d42ab"),
                            Content = "How many doors does this property have?",
                            CreatedOn = new DateTime(2021, 5, 30, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2937),
                            RealEstateId = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("1bd56c5b-ebff-423d-a1a9-6d4e90ff80b7"),
                            Content = "PLEASE ADD ME ON FORTNITE! MY GAMERTAG IS BEASTKILLER_5343",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2966),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("20dd5218-ab86-403f-b605-d61894a2511f"),
                            Content = "This property is so cool!",
                            CreatedOn = new DateTime(2021, 6, 11, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(2996),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("522ea18e-52f7-4ca0-8e66-47b22a48a56a"),
                            Content = "WHAT?! This is my house! Im not selling my house?..",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3024),
                            RealEstateId = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("4a00fc9b-5898-470f-a2a6-654fe483f22f"),
                            Content = "What is wrong with people? This is a chat for the property.",
                            CreatedOn = new DateTime(2021, 6, 4, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3058),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e6"),
                            UserName = "Nisse"
                        },
                        new
                        {
                            Id = new Guid("c5e8f955-aabb-461d-83b3-fa16b846a9bf"),
                            Content = "I like this house, but I also like watermelon, so who am I to have an opinion?",
                            CreatedOn = new DateTime(2021, 6, 5, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3087),
                            RealEstateId = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("54ec667f-d9af-4207-9d03-3a9b1f717dc6"),
                            Content = "This is to expensive? ",
                            CreatedOn = new DateTime(2021, 6, 16, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3116),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("d6b1eac9-0bbd-4ff7-b01a-cbef16d2b6d7"),
                            Content = "I dont wan't this house, im just here to read the comments!",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3150),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2b"),
                            UserName = "Daja"
                        },
                        new
                        {
                            Id = new Guid("b7574518-92b8-4575-8c78-9f378f03cf7c"),
                            Content = "I really do like the interior design!",
                            CreatedOn = new DateTime(2021, 6, 13, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3179),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("61e8b1ab-3676-408f-892c-f59840347d22"),
                            Content = "Great use of space!",
                            CreatedOn = new DateTime(2021, 6, 10, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3209),
                            RealEstateId = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("c40bdc99-113b-4393-8fa7-abc1c44ccff6"),
                            Content = "PLEASE ADD ME ON FORTNITE! MY GAMERTAG IS BEASTKILLER_5343",
                            CreatedOn = new DateTime(2021, 6, 14, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3237),
                            RealEstateId = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("e029516f-0c87-47af-9929-282c3713ed57"),
                            Content = "This is to expensive? ",
                            CreatedOn = new DateTime(2021, 6, 2, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3268),
                            RealEstateId = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("67307633-26bb-4a23-8f03-3307506f9c8e"),
                            Content = "Who's there?",
                            CreatedOn = new DateTime(2021, 5, 29, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3298),
                            RealEstateId = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("0f9f13bf-d93e-4b57-8325-3f39925f6759"),
                            Content = "Eehm, lol?",
                            CreatedOn = new DateTime(2021, 6, 1, 11, 0, 25, 61, DateTimeKind.Local).AddTicks(3326),
                            RealEstateId = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            UserId = new Guid("515b001c-726b-4582-8609-6471833634e7"),
                            UserName = "Classe"
                        });
                });

            modelBuilder.Entity("Entities.Models.RealEstate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CanBeRented")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBeSold")
                        .HasColumnType("bit");

                    b.Property<int>("ConstructionYear")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealEstateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RentingPrice")
                        .HasColumnType("int");

                    b.Property<int>("SellingPrice")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateTypeId");

                    b.ToTable("RealEstates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f97a72cb-5c1b-419a-a1c1-14d318ea22b7"),
                            Address = "Mladost 1A, Telerik Academy building",
                            CanBeRented = true,
                            CanBeSold = true,
                            ConstructionYear = 2005,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 33, DateTimeKind.Local).AddTicks(448),
                            Description = "You will love it. The view is great!",
                            RealEstateTypeId = 1,
                            RentingPrice = 500,
                            SellingPrice = 120000,
                            Title = "Nice Apartment",
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("edc04431-20d9-42d5-9c05-edae58138bba"),
                            Address = "Mladost 2A, Telerik Academy building",
                            CanBeRented = true,
                            CanBeSold = true,
                            ConstructionYear = 2005,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1076),
                            Description = "You will love it. The view is great!",
                            RealEstateTypeId = 1,
                            RentingPrice = 500,
                            SellingPrice = 120000,
                            Title = "Ugly Apartment",
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("d604180f-37d8-4cc5-bfbd-45c904500023"),
                            Address = "Mladost 3A, Telerik Academy building",
                            CanBeRented = true,
                            CanBeSold = true,
                            ConstructionYear = 1990,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1166),
                            Description = "This apartment is not nice, but cheap",
                            RealEstateTypeId = 1,
                            RentingPrice = 300,
                            SellingPrice = 20000,
                            Title = "Very old Apartment",
                            UserId = new Guid("09f047af-baf6-4400-aeb0-260360ecdc03"),
                            UserName = "Adam"
                        },
                        new
                        {
                            Id = new Guid("b0e501a1-bfa8-4fcf-ad7e-5daf590797fe"),
                            Address = "Mladost 23A, Telerik PREMIUM building",
                            CanBeRented = true,
                            CanBeSold = true,
                            ConstructionYear = 2019,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1194),
                            Description = "This is premium living!",
                            RealEstateTypeId = 1,
                            RentingPrice = 2000,
                            SellingPrice = 450000,
                            Title = "EXPENSIVE Apartment",
                            UserId = new Guid("f6b60805-d507-470a-beaa-e020fc012845"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("f30f7fd5-afe5-40f8-9294-7dea56fd106c"),
                            Address = "HouseStreet 23",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2019,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1218),
                            Description = "Perfect house for small family",
                            RealEstateTypeId = 2,
                            RentingPrice = 0,
                            SellingPrice = 350000,
                            Title = "Small house",
                            UserId = new Guid("f6b60805-d507-470a-beaa-e020fc012845"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("c1c32290-5f67-4a19-aa3d-a44fc958b35b"),
                            Address = "HouseStreet 24",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2016,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1264),
                            Description = "Perfect house for a medium sized family",
                            RealEstateTypeId = 2,
                            RentingPrice = 0,
                            SellingPrice = 450000,
                            Title = "Medium house",
                            UserId = new Guid("f6b60805-d507-470a-beaa-e020fc012845"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("f97003cf-751a-401a-b37e-452e966ffc33"),
                            Address = "HouseStreet 27",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2014,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1297),
                            Description = "Perfect house for a big family!",
                            RealEstateTypeId = 2,
                            RentingPrice = 0,
                            SellingPrice = 850000,
                            Title = "GIGANTIC house",
                            UserId = new Guid("f6b60805-d507-470a-beaa-e020fc012845"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("51b4e09d-69da-4130-af68-c319ae70ca52"),
                            Address = "HouseStreet 27",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2014,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1322),
                            Description = "Perfect house for a big family!",
                            RealEstateTypeId = 2,
                            RentingPrice = 0,
                            SellingPrice = 850000,
                            Title = "GIGANTIC house",
                            UserId = new Guid("f6b60805-d507-470a-beaa-e020fc012845"),
                            UserName = "Classe"
                        },
                        new
                        {
                            Id = new Guid("16b1323c-590b-478b-9e20-b02c06817ada"),
                            Address = "Officestreet 33",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2010,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1347),
                            Description = "The perfect office for a medium sized company",
                            RealEstateTypeId = 3,
                            RentingPrice = 0,
                            SellingPrice = 1850000,
                            Title = "Modern Office",
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("ccf6bebe-692c-49ca-85e0-531223869fb9"),
                            Address = "Officestreet 553",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2010,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1369),
                            Description = "The perfect office for a minicompany",
                            RealEstateTypeId = 3,
                            RentingPrice = 0,
                            SellingPrice = 50000,
                            Title = "Mini Office",
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        },
                        new
                        {
                            Id = new Guid("493294d0-ed52-48e8-b517-4a3fc0ab4810"),
                            Address = "Warehousestreet 1",
                            CanBeRented = false,
                            CanBeSold = true,
                            ConstructionYear = 2000,
                            Contact = "0888-888-888",
                            CreatedOn = new DateTime(2021, 6, 3, 11, 0, 25, 34, DateTimeKind.Local).AddTicks(1401),
                            Description = "Gigantic warehouse that was formerly used by Amazon! Can fit 4.000.000 cars inside.",
                            RealEstateTypeId = 4,
                            RentingPrice = 0,
                            SellingPrice = 199240000,
                            Title = "HUGE Warehouse",
                            UserId = new Guid("37afcdde-6387-4e34-aa1e-99d8ae0a9e2a"),
                            UserName = "Marcus"
                        });
                });

            modelBuilder.Entity("Entities.Models.RealEstateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RealEstateTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Name = "House"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Warehouse"
                        });
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.RealEstate", "RealEstate")
                        .WithMany("Comments")
                        .HasForeignKey("RealEstateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("Entities.Models.RealEstate", b =>
                {
                    b.HasOne("Entities.Models.RealEstateType", "PropertyType")
                        .WithMany()
                        .HasForeignKey("RealEstateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Entities.Models.RealEstate", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
